"""`aeiou-datagen`: write the container datasets an abstract declares, through their format
classes, with the runner's payload (`runner/README.md` §5: `aeiou-positional/1` over
`dgen-data` 0.3.0), and the manifest `aeiou run` checks (`schema/README.md` §6).

    aeiou-datagen AST --root DIR [--params-file FILE]… [--param k=v]… [--gpus G]
                      [--dedupe D] [--compress C] [--threads N] [--dataset NAME]… [--config FILE]

`--root` and `--threads` come through the runner's option layers (`options.py`: the command
line, else `AEIOU_ROOT`/`AEIOU_THREADS`, else the `[datagen]` table of the TOML file `--config`
or `AEIOU_CONFIG` names, else the default); the rest is the command line's alone, and the
block of what was resolved, with each value's source, is printed as `aeiou datagen` prints it.

Datasets without a format class are `aeiou datagen`'s (the Rust writer); this tool skips
them, and `aeiou datagen` refuses the ones with a class, so a corpus is written by both, each
dataset by exactly one of them. Names, sizes, offsets, and bytes follow the runner's
definitions bit for bit (`rng.py`, `pattern.py`, `layout.py`); every file is checked against
the geometry its layout predicts before the manifest is written.
"""
from __future__ import annotations

import argparse
import concurrent.futures
import copy
import hashlib
import json
import os
import pathlib
import platform
import socket
import sys
import tempfile
import time

from . import __version__, emit, options, params as params_mod
from .formats import FormatClass
from .layout import FileGeometry, Layout
from .nodes import BuildError
from .pattern import Pattern
from .rng import block_seed, sample_size

MANIFEST_NAME = ".aeiou-dataset.json"
MANIFEST_VERSION = 1
BLOCK = 1 << 20
GENERATOR, GENERATOR_VERSION, WRAPPER = "dgen-data", "0.3.0", "aeiou-positional/1"


# ---- parameters and the resolved definition (payload.rs: param_values, substitute, resolved_dataset) ----

def param_values(ast: dict, sets: list, overrides: list, gpus: int) -> dict:
    values = {k: p["default"] for k, p in ast.get("params", {}).items()}
    for pset in sets:
        values.update(pset["params"])
    for name, text in overrides:
        try:
            values[name] = json.loads(text)
        except ValueError:
            values[name] = text
    values["gpus"] = gpus
    return values


def substitute(v, values: dict):
    if isinstance(v, dict):
        if len(v) == 1 and "param" in v:
            if v["param"] not in values:
                raise BuildError(f"param `{v['param']}` has no value")
            return copy.deepcopy(values[v["param"]])
        return {k: substitute(x, values) for k, x in v.items()}
    if isinstance(v, list):
        return [substitute(x, values) for x in v]
    return v


def canonical_json(v) -> str:
    return json.dumps(v, sort_keys=True, separators=(",", ":"), ensure_ascii=True, allow_nan=False)


def resolved_dataset(ast: dict, name: str, values: dict) -> dict:
    entry = substitute(ast["datasets"][name], values)
    for inner in entry.values():
        if isinstance(inner, dict):
            inner.pop("doc", None)
    return json.loads(canonical_json(entry))


def ev(x) -> int:
    """Evaluate a dataset-level expression (parameters already substituted) to an int."""
    if isinstance(x, bool):
        return int(x)
    if isinstance(x, int):
        return x
    if isinstance(x, float):
        return int(round(x))
    if isinstance(x, dict) and len(x) == 1:
        k, a = next(iter(x.items()))
        if k in ("add", "sub", "mul", "div", "mod", "ceil_div", "min", "max"):
            p, q = ev(a[0]), ev(a[1])
            return {"add": p + q, "sub": p - q, "mul": p * q, "div": p // q if q else 0, "mod": p % q if q else 0,
                    "ceil_div": -(-p // q) if q else 0, "min": min(p, q), "max": max(p, q)}[k]
        if k == "neg":
            return -ev(a)
    raise BuildError(f"cannot evaluate {x!r} at datagen time (dataset-level expressions are over parameters and literals)")


# ---- payload ----

class Payload:
    """The bytes of one file's payload stream: 1 MiB blocks seeded `block_seed(seed, unit, b)`,
    generated by dgen with the compression layout, one block cached."""

    def __init__(self, seed: int, unit: int, compress: int):
        self.seed, self.unit, self.compress = seed, unit, compress
        self._b, self._block = None, b""

    def block(self, b: int) -> bytes:
        if self._b != b:
            import dgen_py
            g = dgen_py.Generator(size=BLOCK, dedup_ratio=1.0, compress_ratio=float(self.compress), numa_mode="disabled",
                                  max_threads=1, block_size=BLOCK, seed=block_seed(self.seed, self.unit, b))
            buf = bytearray(BLOCK)
            n = g.fill_chunk(buf)
            if n != BLOCK:
                raise BuildError(f"dgen filled {n} of {BLOCK} bytes")
            self._b, self._block = b, bytes(buf)
        return self._block

    def __call__(self, off: int, n: int) -> bytes:
        out = []
        while n > 0:
            b, i = divmod(off, BLOCK)
            take = min(n, BLOCK - i)
            out.append(self.block(b)[i:i + take])
            off += take
            n -= take
        return b"".join(out)


# ---- one dataset ----

class Job:
    def __init__(self, ast, name, values, root: pathlib.Path, dedupe: int, compress: int):
        self.ast, self.name, self.values, self.root = ast, name, values, root
        self.resolved = resolved_dataset(ast, name, values)
        body = self.resolved["files"]
        self.fmt = body["format"]
        self.klass = FormatClass.from_spec(self.fmt)
        self.count = ev(body["count"])
        self.spf = ev(body.get("samples_per_file", 1))
        if self.count < 0 or self.spf < 1:
            raise BuildError(f"dataset {name}: count {self.count}, samples_per_file {self.spf}")
        self.files = (self.count + self.spf - 1) // self.spf
        self.layout = Layout.from_spec(self.fmt.get("layout"), self.spf, ev)
        self.size = body["size"]
        self.seed = int(body["seed"])
        self.pattern = Pattern(body["pattern"])
        self.rel_root = self.pattern.root()
        self.dedupe, self.compress = max(1, dedupe), max(1, compress)
        self.units_dedupe = max(1, -(-self.files // self.dedupe))

    def sizes(self, file: int) -> list:
        first = file * self.spf
        n = min(self.spf, self.count - first)
        return [sample_size(self.size, self.seed, first + i) for i in range(n)]

    def write(self, file: int) -> tuple:
        sizes = self.sizes(file)
        geo = FileGeometry(self.layout, sizes)
        rel = self.pattern.format(id=file)
        path = self.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = Payload(self.seed, file % self.units_dedupe, self.compress)
        self.klass.write_file(str(path), file * self.spf, sizes, payload, geo)
        self.klass.check_file(str(path), sizes, geo)
        return len(sizes), geo.file_size

    def manifest(self, files_written: int, bytes_written: int, started: float, provenance: dict) -> dict:
        m = {"manifest_version": MANIFEST_VERSION, "dataset": self.resolved,
             "payload": {"generator": GENERATOR, "version": GENERATOR_VERSION, "wrapper": WRAPPER, "block": BLOCK,
                         "dedupe": self.dedupe, "compress": self.compress},
             "format": {"class": self.fmt["class"], "reader": self.fmt.get("reader"), "version": self.fmt.get("version"),
                        "writer": self.klass.library()}}
        m["provenance"] = {**provenance, "datagen": f"aeiou-datagen {__version__}", "host": socket.gethostname(),
                           "python": platform.python_version(), "started": int(started), "finished": int(time.time()),
                           "files_written": files_written, "bytes_written": bytes_written}
        return m

    @staticmethod
    def manifest_id(m: dict) -> str:
        normative = {k: m[k] for k in ("manifest_version", "dataset", "payload", "format")}
        return hashlib.sha256(canonical_json(normative).encode()).hexdigest()


def write_manifest(dir_: pathlib.Path, m: dict) -> pathlib.Path:
    path = dir_ / MANIFEST_NAME
    fd, tmp = tempfile.mkstemp(prefix=MANIFEST_NAME + ".tmp.", dir=str(dir_))
    with os.fdopen(fd, "w") as f:
        f.write(json.dumps(m, indent=2) + "\n")
    os.replace(tmp, path)
    return path


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="aeiou-datagen", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("ast", type=pathlib.Path)
    ap.add_argument("--root", type=pathlib.Path, help="directory the abstract's paths are relative to (or $AEIOU_ROOT, or [datagen] root in --config)")
    ap.add_argument("--params-file", action="append", default=[], type=pathlib.Path, metavar="FILE")
    ap.add_argument("--param", action="append", default=[], metavar="NAME=VALUE")
    ap.add_argument("--gpus", type=int, default=1)
    ap.add_argument("--dedupe", type=int, default=1)
    ap.add_argument("--compress", type=int, default=1)
    ap.add_argument("--threads", type=int, help="writer threads (default: all cores; or $AEIOU_THREADS, or [datagen] threads in --config)")
    ap.add_argument("--dataset", action="append", default=[], metavar="NAME")
    ap.add_argument("--config", type=pathlib.Path, metavar="FILE", help="a TOML config file (else $AEIOU_CONFIG, else none; never searched for)")
    ap.add_argument("--version", action="version", version=f"aeiou-datagen {__version__}")
    a = ap.parse_args(argv)
    try:
        return _main(a)
    except BuildError as e:
        print(f"FAIL {e}", file=sys.stderr)
        return 1


def resolve(a) -> options.Layers:
    """`aeiou datagen`'s layers (main.rs `datagen_cmd`): the shape and the writer's fixed
    options first, then `root` and `threads` through the layers. Sets `a.root` and
    `a.threads` to the values in effect."""
    layers = options.Layers("datagen", a.config)
    layers.fixed("abstract", a.ast, True)
    layers.fixed("param", a.param, bool(a.param))
    layers.fixed("params-file", a.params_file, bool(a.params_file))
    layers.fixed("gpus", a.gpus, a.gpus != 1)
    layers.fixed("dedupe", a.dedupe, a.dedupe != 1)
    layers.fixed("compress", a.compress, a.compress != 1)
    layers.fixed("dataset", a.dataset, bool(a.dataset))
    a.root = layers.layered("root", a.root, pathlib.Path)
    if a.root is None:
        raise BuildError("--root DIR is required (the command line, $AEIOU_ROOT, or [datagen] root in the config file)")
    a.threads = layers.layered("threads", a.threads, int)
    if a.threads is None:
        a.threads = os.cpu_count() or 1
    layers.finish()
    return layers


def _main(a) -> int:
    from .validate import validate
    layers = resolve(a)
    ast = emit.load(a.ast)
    validate(ast)
    sha = emit.sha256(ast)
    sets = []
    for p in a.params_file:
        pset = params_mod.load(p)
        errors = params_mod.check(ast, pset, ast_sha256=sha, name=p.name)
        if errors:
            raise BuildError("\n  ".join(errors))
        sets.append(pset)
    overrides = []
    for s in a.param:
        if "=" not in s:
            raise BuildError(f"--param {s}: expected NAME=VALUE")
        k, v = s.split("=", 1)
        if k not in ast.get("params", {}):
            raise BuildError(f"--param {k}: no such parameter")
        overrides.append((k, v))
    values = param_values(ast, sets, overrides, a.gpus)
    print(f"abstract {ast['name']}  sha256 {sha}")
    layers.print()
    provenance = {"abstract": ast["name"], "ast_sha256": sha, "params": values,
                  "param_files": [{"path": str(p), "sha256": params_mod.file_sha256(p)} for p in a.params_file]}
    wanted = set(a.dataset)
    done = 0
    for name, d in ast.get("datasets", {}).items():
        has_format = "files" in d and "format" in d["files"]
        if wanted and name not in wanted:
            continue
        if not has_format:
            if wanted:
                raise BuildError(f"dataset `{name}` has no format class: `aeiou datagen` (the Rust writer) writes it")
            print(f"dataset {name}: no format class, left to `aeiou datagen`")
            continue
        job = Job(ast, name, values, a.root, a.dedupe, a.compress)
        root = a.root / job.rel_root
        if root.exists() and any(root.iterdir()):
            raise BuildError(f"dataset `{name}`: {root} is not empty; datasets are read-only, remove it first")
        root.mkdir(parents=True, exist_ok=True)
        started = time.time()
        files_written = bytes_written = 0
        with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, a.threads)) as ex:
            last = time.time()
            for i, (n, b) in enumerate(ex.map(job.write, range(job.files))):
                files_written += 1
                bytes_written += b
                if time.time() - last > 5:
                    last = time.time()
                    print(f"  {name}: {i + 1}/{job.files} files, {bytes_written / 2**20:.1f} MiB written")
        m = job.manifest(files_written, bytes_written, started, provenance)
        write_manifest(root, m)
        print(f"dataset {name}: {files_written} file(s), {bytes_written / 2**20:.2f} MiB in {time.time() - started:.2f}s at {root}  "
              f"id {Job.manifest_id(m)}  ({job.klass.name}, {job.klass.library()})")
        done += 1
    if wanted and done < len(wanted):
        raise BuildError(f"not every --dataset was found: {sorted(wanted)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
