"""Canonical form, hash, provenance, and the YAML writer."""
from __future__ import annotations

import hashlib
import json
import pathlib
import platform
import subprocess
import sys

import yaml

from . import __version__
from .nodes import BuildError

# Values the hermetic harness computes before it installs the audit hooks (git and the
# lockfile need subprocesses and file reads the sandbox denies).
PRECOMPUTED: dict = {}


def canonical(ast: dict) -> bytes:
    """Sorted keys, no whitespace, ASCII escapes, floats in Python repr, provenance removed.
    Identical to schema/check.py."""
    stripped = {k: v for k, v in ast.items() if k != "provenance"}
    return json.dumps(stripped, sort_keys=True, separators=(",", ":"), ensure_ascii=True,
                      allow_nan=False).encode()


def sha256(ast: dict) -> str:
    return hashlib.sha256(canonical(ast)).hexdigest()


def file_sha256(path) -> str:
    return hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()


def git_describe(path) -> str | None:
    """Short HEAD of the repository holding `path`, with `-dirty` if `path` has uncommitted
    changes or is untracked. None outside a repository."""
    path = pathlib.Path(path).resolve()
    try:
        head = subprocess.run(["git", "-C", str(path.parent), "rev-parse", "--short=12", "HEAD"],
                              capture_output=True, text=True, timeout=10)
        if head.returncode:
            return None
        status = subprocess.run(["git", "-C", str(path.parent), "status", "--porcelain", "--", str(path)],
                                capture_output=True, text=True, timeout=10)
        dirty = "-dirty" if status.stdout.strip() else ""
        return head.stdout.strip() + dirty
    except (OSError, subprocess.SubprocessError):
        return None


def find_lock(start) -> pathlib.Path | None:
    for parent in [pathlib.Path(start).resolve(), *pathlib.Path(start).resolve().parents]:
        for name in ("uv.lock", "requirements.lock"):
            if (parent / name).exists():
                return parent / name
    return None


def provenance(script, ast: dict, *, built_twice: bool | None = None) -> dict:
    """The provenance block (not part of the hash)."""
    script = pathlib.Path(script)
    pre = PRECOMPUTED.get(str(script.resolve()), {})
    gen = {"script": script.name, "sha256": pre.get("script_sha256") or file_sha256(script),
           "builder_version": __version__}
    git = pre["git"] if "git" in pre else git_describe(script)
    if git:
        gen["git"] = git
    out = {"generator": gen, "python": platform.python_version()}
    lock = pre.get("lock")
    if lock is None and "lock" not in pre:
        lp = find_lock(script.parent)
        lock = {"file": lp.name, "sha256": file_sha256(lp)} if lp else None
    if lock:
        out["lock"] = lock
    if built_twice is not None:
        out["built_twice_identical"] = built_twice
    out["ast_sha256"] = sha256(ast)
    return out


class _Dumper(yaml.SafeDumper):
    pass


def _represent_str(dumper, data):
    style = '"' if (data == "" or data[0] in ".-{}[]!&*#|>%@`'\"" or ":" in data
                    or data.strip() != data or data in ("null", "true", "false")) else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_Dumper.add_representer(str, _represent_str)


def render(ast: dict, prov: dict | None = None, header: str | None = None) -> str:
    doc = dict(ast)
    if prov:
        doc["provenance"] = prov
    text = yaml.dump(doc, Dumper=_Dumper, sort_keys=False, default_flow_style=None, width=110,
                     allow_unicode=True)
    if header:
        text = "".join(f"# {line}\n" if line else "#\n" for line in header.splitlines()) + text
    return text


def load(path) -> dict:
    return yaml.safe_load(pathlib.Path(path).read_text())


def write(wl, path=None, *, provenance: bool = True, built_twice: bool | None = None):
    ast = wl.build()
    path = pathlib.Path(path) if path else pathlib.Path(f"{wl.name}.ast.yaml")
    if path.is_dir():
        path = path / f"{wl.name}.ast.yaml"
    prov = None
    if provenance:
        prov = globals()["provenance"](wl.source, ast, built_twice=built_twice)
    header = (f"{wl.name}: generated by aeiou {__version__} from {pathlib.Path(wl.source).name}; "
              f"do not edit.\nast sha256 {sha256(ast)}")
    text = render(ast, prov, header)
    if len(text) > 16 * 1024 * 1024:
        raise BuildError("AST too large")
    path.write_text(text)
    return path
